# Generated by Django 5.2.6 on 2025-09-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='creatd_at',
            new_name='created_at',
        ),
    ]
