# Generated by Django 5.2.6 on 2025-09-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_booking_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='creatd_at',
            new_name='created_at',
        ),
    ]
