# Generated by Django 5.2.6 on 2025-11-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_review_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='property_id',
            new_name='listing_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
