# Generated by Django 5.2.6 on 2025-11-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_property_id_listing_listing_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='host_id',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
