# Generated by Django 5.2.6 on 2025-11-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tx_ref',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
