# Generated by Django 5.2.6 on 2025-11-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_payment_tx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tx_ref',
            field=models.UUIDField(unique=True),
        ),
    ]
